version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev2
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:buster"